name: super_secure
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  android_intent: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^2.0.0
  # geolocator: ^9.0.1
  http: ^0.13.4
  local_auth: ^2.1.0
  location: ^4.4.0
  # permission_handler: ^9.2.0
  screen_capture_event: ^1.0.3
  toast: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
